// src/components/shared/mockData.ts
import type { UniCartClass } from "./constants";

export const mockClassLibrary: UniCartClass[] = [
  { id: "1",  sectionId: "15001", subject: "COMP", number: "110",  title: "Intro to Algorithms",        units: 3, semester: "Spring 2026", professor: "Dr. Smith",    days: ["Mon","Wed"],       startTime: "09:00", endTime: "10:15", location: "JD 1600",  isOnline: false, seats: 35, seatsAvailable: 12, tags: ["CS Core","Lower Division"] },
  { id: "2",  sectionId: "15002", subject: "COMP", number: "182",  title: "Programming in Python",      units: 3, semester: "Spring 2026", professor: "Dr. Lee",      days: ["Tue","Thu"],       startTime: "11:00", endTime: "12:15", location: "JD 2200",  isOnline: false, seats: 30, seatsAvailable: 5,  tags: ["CS Core","Lower Division"] },
  { id: "3",  sectionId: "15003", subject: "MATH", number: "150A", title: "Calculus I",                 units: 4, semester: "Spring 2026", professor: "Dr. Patel",    days: ["Mon","Wed","Fri"], startTime: "08:00", endTime: "08:50", location: "SN 323",   isOnline: false, seats: 40, seatsAvailable: 20, tags: ["Lower Division"] },
  { id: "4",  sectionId: "15004", subject: "ENGL", number: "115",  title: "College Writing",            units: 3, semester: "Spring 2026", professor: "Prof. Torres", days: ["Tue","Thu"],       startTime: "14:00", endTime: "15:15", location: "SQ 110",   isOnline: false, seats: 25, seatsAvailable: 8,  tags: ["GE: Basic Skills","Lower Division"] },
  { id: "5",  sectionId: "15005", subject: "COMP", number: "380",  title: "Data Structures",            units: 3, semester: "Spring 2026", professor: "Dr. Chen",     days: ["Mon","Wed"],       startTime: "13:00", endTime: "14:15", location: "JD 1600",  isOnline: false, seats: 30, seatsAvailable: 0,  waitlistCount: 6, tags: ["CS Core","Upper Division"] },
  { id: "6",  sectionId: "15006", subject: "PHYS", number: "220A", title: "Physics for Engineers I",    units: 4, semester: "Spring 2026", professor: "Dr. Kim",      days: ["Tue","Thu"],       startTime: "09:30", endTime: "10:45", location: "SN 108",   isOnline: false, seats: 35, seatsAvailable: 15, linkedLab: "15007", tags: ["Engineering Core"] },
  { id: "7",  sectionId: "15007", subject: "PHYS", number: "220AL",title: "Physics Lab I",              units: 1, semester: "Spring 2026", professor: "Dr. Kim",      days: ["Fri"],             startTime: "13:00", endTime: "15:50", location: "SN 110L",  isOnline: false, seats: 20, seatsAvailable: 15, tags: ["Engineering Core"] },
  { id: "8",  sectionId: "15008", subject: "BUS",  number: "302",  title: "Business Communications",    units: 3, semester: "Spring 2026", professor: "Prof. Martinez",days: [],                 startTime: "",      endTime: "",      isOnline: true,        seats: 50, seatsAvailable: 22, tags: ["Online","Upper Division"] },
  { id: "9",  sectionId: "15009", subject: "HIST", number: "111",  title: "World History to 1500",      units: 3, semester: "Spring 2026", professor: "Dr. Johnson",  days: ["Mon","Wed","Fri"], startTime: "10:00", endTime: "10:50", location: "SQ 220",   isOnline: false, seats: 45, seatsAvailable: 30, tags: ["GE: Humanities","Lower Division"] },
  { id: "10", sectionId: "15010", subject: "COMP", number: "490",  title: "Senior Design Project",      units: 3, semester: "Spring 2026", professor: "Dr. Williams", days: ["Thu"],             startTime: "16:00", endTime: "18:45", location: "JD 3300",  isOnline: false, seats: 20, seatsAvailable: 4,  tags: ["CS Required","Upper Division"] },
  { id: "11", sectionId: "15011", subject: "ART",  number: "101",  title: "Drawing I",                  units: 3, semester: "Spring 2026", professor: "Prof. Davis",  days: ["Mon","Wed"],       startTime: "11:00", endTime: "12:15", location: "FA 225",   isOnline: false, seats: 20, seatsAvailable: 7,  tags: ["GE: Arts","Lower Division"] },
  { id: "12", sectionId: "15012", subject: "BIOL", number: "101",  title: "Fundamentals of Biology",    units: 3, semester: "Spring 2026", professor: "Dr. Nguyen",   days: ["Tue","Thu"],       startTime: "13:00", endTime: "14:15", location: "SN 201",   isOnline: false, seats: 50, seatsAvailable: 18, tags: ["GE: Science","Lower Division"] },
  { id: "13", sectionId: "15013", subject: "PSYC", number: "150",  title: "General Psychology",         units: 3, semester: "Spring 2026", professor: "Dr. Clark",    days: [],                  startTime: "",      endTime: "",      isOnline: true,        seats: 60, seatsAvailable: 35, tags: ["Online","GE: Social Sciences","Lower Division"] },
  { id: "14", sectionId: "15014", subject: "KINE", number: "100",  title: "Health & Physical Activity", units: 1, semester: "Spring 2026", professor: "Prof. Garcia", days: ["Fri"],             startTime: "10:00", endTime: "10:50", location: "PE 103",   isOnline: false, seats: 30, seatsAvailable: 10, tags: ["GE: Lifelong Learning","Lower Division"] },
  { id: "15", sectionId: "15015", subject: "COMP", number: "524",  title: "Machine Learning",           units: 3, semester: "Spring 2026", professor: "Dr. Zhao",     days: ["Tue","Thu"],       startTime: "16:00", endTime: "17:15", location: "JD 3300",  isOnline: false, seats: 25, seatsAvailable: 3,  tags: ["CS Elective","Graduate"] },
  // Fall 2026
  { id: "16", sectionId: "16001", subject: "COMP", number: "110",  title: "Intro to Algorithms",        units: 3, semester: "Fall 2026",   professor: "Dr. Smith",    days: ["Mon","Wed"],       startTime: "09:00", endTime: "10:15", location: "JD 1600",  isOnline: false, seats: 35, seatsAvailable: 35, tags: ["CS Core","Lower Division"] },
  { id: "17", sectionId: "16002", subject: "MATH", number: "280",  title: "Applied Calculus",           units: 3, semester: "Fall 2026",   professor: "Dr. Patel",    days: ["Tue","Thu"],       startTime: "10:00", endTime: "11:15", location: "SN 323",   isOnline: false, seats: 40, seatsAvailable: 28, tags: ["Lower Division"] },
  { id: "18", sectionId: "16003", subject: "ENGL", number: "215",  title: "Technical Writing",          units: 3, semester: "Fall 2026",   professor: "Prof. Torres", days: ["Mon","Wed","Fri"], startTime: "13:00", endTime: "13:50", location: "SQ 110",   isOnline: false, seats: 25, seatsAvailable: 12, tags: ["Upper Division"] },
];
